### PR TITLE
Mention that import.meta.dirname is built-in now

### LINKED ISSUE #6: Mention that `import.meta.dirname`/ `input.meta.filename` are now available built-in?
Available as `import.meta.dirname` and `input.meta.filename` since Node.js 20.11.0 and 21.2.0: https://nodejs.org/api/esm.html#importmetadirname

Added in: https://github.com/nodejs/node/pull/48740

### PR DESCRIPTION
**Pull request by voxpelli**
Fixes #6

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I wish to deprecate this module one day.

**Comment by voxpelli** [comment]
@mcollina You didn't merge?

**Comment by mcollina** [comment]
Wrong button

**Pull request merged**
